### ISSUE TITLE
pandoc eps handling?

### ISSUE THREAD

**Issue by jasongoodwin** [kbonne/pandoc-plantuml-filter#1]
Hey, 
I'm getting an error on osx related to eps:

hdochs-MacBook-Air:pandoc-plantuml-filter admin$  pandoc ./README.md --variable=geometry:a4paper,margin=2cm --variable=fontsize:11pt -o ./README.pdf --filter ./dist/build/pandoc-plantuml-filter/pandoc-plantuml-filter
pandoc: Unable to convert image `dba2905531256f9ebf116f41123f91f40a6e51e9.eps':
Cannot load file
Jpeg Invalid marker used
PNG Invalid PNG file, signature broken
Bitmap Invalid Bitmap magic identifier
GIF Invalid Gif signature : %!PS-A
HDR Invalid radiance file signature
Tiff Invalid endian tag value

I tried to sort this out but i'm not sure what I need for eps support here.
I'm working on a more descriptive installation on a fork - any support much appreciated.

**Comment by jasongoodwin** [comment]
You know what, it's actually working. 
I get a bunch of noisy output but I'm getting a pdf after installing the full maxtex

hdochs-MacBook-Air:pandoc-plantuml-filter admin$ pandoc ./README.md --variable=geometry:a4paper,margin=2cm --variable=fontsize:11pt -o ./README.pdf --filter ./dist/build/pandoc-plantuml-filter/pandoc-plantuml-filter
pandoc: Unable to convert image `dba2905531256f9ebf116f41123f91f40a6e51e9.eps':
Cannot load file
Jpeg Invalid marker used
PNG Invalid PNG file, signature broken
Bitmap Invalid Bitmap magic identifier
GIF Invalid Gif signature : %!PS-A
HDR Invalid radiance file signature
Tiff Invalid endian tag value

PDF file is still generated!
I'm working on instructions for the noob here if anyone is struggling: https://github.com/jasongoodwin/pandoc-plantuml-filter
Covers OSX at least.

Thanks so much for this project! Works like a charm.

**Comment by kbonne** [comment]
Sorry, I missed this comment completely - should check my SPAM filter!

Could you be so kind to create a pull request with your build instructions on OSX?
I'm not a big fan of keeping binaries in a repo though :blush: 

Thank you in advance!

Kurt

**Comment by jasongoodwin** [comment]
Hey,
I put the binary in the repo because I'm asking some devs to use this and they don't know what Haskell is let alone how to build things :P

I'll make a pretty PR - I just got a new laptop so I'll run through the install process one more time (I need to get setup again anyway).

Thanks for the tool - this really helped me out.
