### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by stevepowell99** [kbonne/pandoc-plantuml-filter#2]
looks very interesting, but how do I install it?

**Comment by byzheng** [comment]
I have the same question.

**Comment by kbonne** [comment]
Currently the only option is to build is from source and then use the filter using pandoc's `--filter` option as described in the README.

If anyone is interested, I can try to provide packages and/or binaries.

I must admit this was a toy project, but as it seems to be useful for others as well, I'm willing to improve it and make it more usable.

@stevepowell99 @byzheng : Would this help you and if so, what platforms are you using?

**Comment by byzheng** [comment]
@kbonne Thanks for your reply. I am working to write some documents which mix with software development and scientific report. It will be really handy if I can plot my diagram using plantuml in my markdown file. Although I am using RMarkdown, but can figure out how to implement it in Rmarkdown if your filter is working for markdown.

I am using Windows 7 and Ubuntu operating system, and pandoc to process markdown file (1.13.1). Please let me know if you need more information. Happy to test it if you like.

**Comment by stevepowell99** [comment]
Not a toy for me! Actually I use your work indirectly via https://github.com/getpelican/pelican-plugins/pull/376: mikitex uses it to make plantuml work with pelican. I wanted to use the same simplicity when writing in markdown outside of pelican. I would be very interested in packages and am interested in helping to test. I am using ubuntu 14.04 64-bit and mostly write with sublimetext.

**Comment by kbonne** [comment]
I updated README.md with basic install instructions, both from code and using ubuntu packages.
Must say I never did this before, so hope all goes fine :-)

Please let me know if this helps.

Thank you for your input!

Kurt
